apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    version: "1"
  name: nginx
  namespace: rubyapp
spec:
  ports:
  - port: 8020
    protocol: TCP
    targetPort: 8020
    nodePort: 30007
  selector:
    app: nginx
    version: "1"
status:
  loadBalancer: {}
