apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rubyapp
  name: nginx-deployment
  labels:
    app: nginx
    version: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: "1"
  template:
    metadata:
      labels:
        app: nginx
        version: "1"
    spec:
      containers:
      - name: nginx
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
        image: anas149037/nginx-rubyapp:latest
        ports:
        - containerPort: 8020
       