apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    version: "1"
  name: nginx
  namespace: rubyapp
spec:
  ports:
  - nodePort: 32477
    port: 8020
    protocol: TCP
    targetPort: 8020
  selector:
    app: nginx
    version: "1"
  type: NodePort
status:
  loadBalancer: {}
