apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rubyapp
  name: redis-deployment
  labels:
    app: redis
    version: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      version: "1"
  template:
    metadata:
      labels:
        app: redis
        version: "1"
    spec:
      containers:  
      - name: redis
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        image: redis:7.0
        volumeMounts:
        - mountPath: /var/lib/redis/data
          name: redis-data
        ports:
          - containerPort: 6379
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pv-claim