apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: rubyapp
spec:
  storageClassName: manual
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/redis