
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    version: "1"
  name: redis-deployment
  namespace: rubyapp
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    version: "1"
status:
  loadBalancer: {}
