
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    version: "1"
  name: postgres
  namespace: rubyapp
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
    version: "1"
status:
  loadBalancer: {}
